### ISSUE TITLE
CSS - image

### ISSUE THREAD

**Issue by chochinlu** [chochinlu/blog#125]
## 用CSS讓圖片可以置中且保持比例縮放於指定框尺寸

``` html
<div class="frame">
  <img src="foo"/>
</div>
```

``` css
.frame {  
    height: 160px; /*can be anything*/
    width: 160px; /*can be anything*/
    position: relative;
}
img {  
    max-height: 100%;  
    max-width: 100%; 
    width: auto;
    height: auto;
    position: absolute;  
    top: 0;  
    bottom: 0;  
    left: 0;  
    right: 0;  
    margin: auto;
}
```
