### ISSUE TITLE
Gitlab CI/CD - .gitlab-ci.yml

### ISSUE THREAD

**Issue by chochinlu** [chochinlu/blog#275]
[全部reference參考](https://docs.gitlab.com/ee/ci/yaml/README.html)

可以在 gitlab instance 的 CI/CD -> pipelines 裡面有個 CI Lint 可以把 .gitlab-ci 貼上去檢查看有無正確

基本例子: 

``` yml
build-job:
    stage: build
    script:
        - echo "Hello,  $GITLAB_USER_LOGIN!"
    tags:
        - test-ci


test-job1:
    stage: test
    script:
        - echo "test-job1 -> This job tests something"
    tags:
        - test-ci

test-job2:
    stage: test
    script:
        - echo "test-job2 -> This job tests something, but takes more time than test-job1."
        - echo "test-job2 ->  After the echo commands complete, it runs the sleep command for 20 seconds"
        - echo "test-job2 -> which simulates a test that runs 20 seconds longer than test-job1"
        - sleep 20
    tags:
        - test-ci

deploy-prod:
    stage: deploy
    script:
        - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    tags:
        - test-ci
```
